version: "3.9"
services:
  db:
    container_name: postgres_clients
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: "clientDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"


  app:
    container_name: rest
    build:
      dockerfile: app.Dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/clientDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db

volumes:
  database_data:
    driver: local
